# Generated by Django 5.2.8 on 2025-11-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('booking_time', models.TimeField(verbose_name='Время бронирования')),
                ('duration', models.IntegerField(choices=[(1, '1 час'), (2, '2 часа'), (3, '3 часа'), (4, '4 часа')], default=1, verbose_name='Продолжительность')),
                ('guests', models.IntegerField(default=1, verbose_name='Количество гостей')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
