# Generated by Django 5.2.8 on 2025-12-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'managed': False, 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='demo',
            options={'managed': False, 'verbose_name': 'Демо', 'verbose_name_plural': 'Демо'},
        ),
        migrations.AlterModelOptions(
            name='gamingstation',
            options={'managed': False, 'verbose_name': 'Игровая станция', 'verbose_name_plural': 'Игровые станции'},
        ),
        migrations.AlterModelOptions(
            name='gamingzone',
            options={'managed': False, 'verbose_name': 'Игровая зона', 'verbose_name_plural': 'Игровые зоны'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False, 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='shifts',
            options={'managed': False, 'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'managed': False, 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'managed': False, 'verbose_name': 'Посетитель', 'verbose_name_plural': 'Посетители'},
        ),
        migrations.AlterModelOptions(
            name='visits',
            options={'managed': False, 'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
    ]
