# Generated by Django 5.2.8 on 2025-12-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_bookings_options_alter_demo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('booking_time', models.TimeField(verbose_name='Время бронирования')),
                ('duration', models.IntegerField(default=1, verbose_name='Продолжительность (часы)')),
                ('guests', models.IntegerField(default=1, verbose_name='Количество гостей')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Бронирование с сайта',
                'verbose_name_plural': 'Бронирования с сайта',
                'ordering': ['-booking_date', '-booking_time'],
            },
        ),
        migrations.DeleteModel(
            name='SimpleBooking',
        ),
    ]
