# Generated by Django 5.2.6 on 2025-12-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_websitebooking_delete_simplebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена (₽)')),
                ('category', models.CharField(choices=[('coffee', 'Кофе'), ('tea', 'Чай'), ('soda', 'Лимонады/Коктейли'), ('energy', 'Энергетики'), ('alcohol', 'Алкогольные коктейли'), ('cold', 'Холодные напитки'), ('hot', 'Горячие напитки'), ('snack', 'Закуски/Десерты')], max_length=20, verbose_name='Категория')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на изображение')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Объем')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
                'ordering': ['category', 'price'],
            },
        ),
    ]
